#!/usr/bin/env python

from keystoneclient.v2_0 import client as keystone_client
from sys import exit
from sys import argv
from sys import stderr
import json
from datetime import datetime
import re


def get_host_port(url):
    m = re.match('https?://(\d+\.\d+\.\d+\.\d+):(\d+)',url)
    if m:
        return (m.group(1),m.group(2))

if __name__ == '__main__':

    if (len(argv) != 5):    
        print "Usage: %s AUTH_URL TENANT USERNAME PASSWORD" % argv[0]
        exit(2)
    else:
        (AUTH_URL,TENANT,USERNAME,PASSWORD) = argv[1:]

    conn = keystone_client.Client(username=USERNAME, password=PASSWORD, tenant_name=TENANT, auth_url=AUTH_URL)

    services = []
    for e in conn.endpoints.list():
        host = get_host_port(e.publicurl)
        if e.enabled:
            service = conn.services.get(e.service_id)
            services.append({'{#SERVICENAME}':service.name, '{#SERVICEURL}':e.publicurl, '{#SERVICEHOST}':host[0], '{#SERVICEPORT}':host[1] })

    print json.dumps({'data':services},sort_keys=True,indent=7,separators=(',',':'))
